
main.o: main.cpp
	/usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 main.cpp -o main
#g++ -std=c++11 -o main main.cpp -lgmsh

run: main.cpp
	#g++ -std=c++11 -o main main.cpp
	/usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 main.cpp -o main
	./main

clean:
	rm *.o output